modLoader="javafml"
loaderVersion="[36,)"
license="NWTG Public License 1.0"

[[mods]]
modId="nwtg_automation"
version="0.1.0"
displayName="NWTG Automation"
credits="MCreator, Forge, Mojang"
displayURL="https://github.com/northwesttrees-gaming/NWTG-Automation"
logoFile="logo.png"
authors="NorthWestTrees Gaming"
description='''
A mod to make things automated one block at a time!
'''

[[dependencies.nwtg_automation]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




