modLoader="javafml"
loaderVersion="[36,)"
license="NWTG Public License 1.0"

[[mods]]
modId="nwtg_automation"
version="0.2.0"
displayName="NWTG Automation"
credits="MCreator, Forge, Mojang"
displayURL="https://northwesttrees-gaming.github.io/mods/nwtg-automation.html"
updateJSONURL="https://raw.githubusercontent.com/northwesttrees-gaming/northwesttrees-gaming.github.io/main/mods/nwtg-automation/updates/mod-updates.json"
logoFile="logo.png"
authors="NorthWestTrees Gaming"
description='''
A mod to make things automated one block at a time!
'''

[[dependencies.nwtg_automation]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




