blank_issues_enabled: false
contact_links:
  - name: "Feature Requests"
    url: https://github.com/northwesttrees-gaming/NWTG-Automation/discussions/categories/feature-requests
    about: Request features on our discussions tab here.
